/**
 * Vantaa DC01-NWP HOST to DISPLAY HOST API 
 * API for Vantaa DC01 between NETWORK HOST [NWP] and DISPLAY HOST [DHP].  You can find out more about Smartlabs DC01 at [https://smartlabsinc.com](h://smartlabsinc.com).   For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@smartlabsinc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model._
import org.json4s._
import scala.reflect.ClassTag

object EnumsSerializers {

  def all: Seq[Serializer[_]] = Seq[Serializer[_]]() :+
    new EnumNameSerializer(DialswitchEnums.LightMode) :+
    new EnumNameSerializer(KeypadswitchEnums.LightMode) :+
    new EnumNameSerializer(LightModeEnums.LightMode) :+
    new EnumNameSerializer(OrderEnums.Status) :+
    new EnumNameSerializer(OutletEnums.TopLevel) :+
    new EnumNameSerializer(OutletEnums.BottomLevel) :+
    new EnumNameSerializer(PaddleswitchEnums.LightMode) :+
    new EnumNameSerializer(PetEnums.Status)

  private class EnumNameSerializer[E <: Enumeration: ClassTag](enum: E)
    extends Serializer[E#Value] {
    import JsonDSL._

    val EnumerationClass: Class[E#Value] = classOf[E#Value]

    def deserialize(implicit format: Formats):
    PartialFunction[(TypeInfo, JValue), E#Value] = {
      case (t @ TypeInfo(EnumerationClass, _), json) if isValid(json) =>
        json match {
          case JString(value) =>
            enum.withName(value)
          case value =>
            throw new MappingException(s"Can't convert $value to $EnumerationClass")
        }
    }

    private[this] def isValid(json: JValue) = json match {
      case JString(value) if enum.values.exists(_.toString == value) => true
      case _ => false
    }

    def serialize(implicit format: Formats): PartialFunction[Any, JValue] = {
      case i: E#Value => i.toString
    }
  }

}
